# Generated by Django 6.0.5 on 2026-06-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagerecord',
            name='triage_status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged')], default='WAITING', max_length=20),
        ),
    ]
